### ISSUE TITLE
Problem: [/currency/x] Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1259]
Problem: typing into the add currencies box produces the following console error:
`Cannot read property 'map' of undefined`

**Comment by AshHimself** [comment]
@blockrazorbot claim

**Comment by AshHimself** [comment]
@gazhayes where abouts are you getting this? On submission? 

On another note, we really need to get the inline error messages working on this page, not sure if we ended up making a ticket for that.

**Comment by gazhayes** [comment]
It looked like it was happening onKeyUp on the exchange field.

**Comment by AshHimself** [comment]
@gazhayes - ok so looks like this exchange menu has changed a little bit since a few days ago and the reasons we are getting all these errors are due to exchanges not being available. Can you help me out with the workflow a little.

If a currency has no exchanges when and where do they add these? Via the Create exchange I assume? I am trying to add a new one now but the button is constantly disable (another bug)?

**Comment by gazhayes** [comment]
> I am trying to add a new one now but the button is constantly disable (another bug)?

Ah that's probably the root cause then.

**Comment by AshHimself** [comment]
@gazhayes I think this ticket is best for @janat08 to look at as there are a few typeahead tickets open and I think they are all related to this issue and may take me a lot longer to resolve and don't want to waste hours.

**Comment by AshHimself** [comment]
@blockrazorbot unclaim

**Comment by chamidu-supeshala** [comment]
I will take a look and try to solve this.
@blockrazorbot claim

**Comment by gazhayes** [comment]
This is another symptom of #1236 not being completed properly.

**Comment by chamidu-supeshala** [comment]
fixed in #1265.
@gazhayes now add exchange and create exchange working properly in [/currency/x]
(other than the `typeahead-component` bugs such as firing 'add' event twice, which already raised)

I will move on to other symptoms of  #1236 tonight

@blockrazorbot label "done"
@blockrazorbot remove "in progress"

**Comment by gazhayes** [comment]
Just to be clear, I'm not sure if you missed this in in #1236 or not, but exchanges are unique objects and have to be in their own collection otherwise all the data about all exchanges has to be repeated on every currency that is listed (in the real world) on that exchange. The name of the exchange (and maybe an _id or slug) should be denormalized into the currencies collection for speed purposes but an exchange will end up with much more data than just the name.

**Comment by chamidu-supeshala** [comment]
currently, the new exchanges added to their own collection. And for each currency, the id, name and slug of tagged exchanges included like this. (speed purposes)

![screenshot from 2018-04-22 15-55-10](https://user-images.githubusercontent.com/27463355/39093965-dbb8d5d4-4645-11e8-9eac-7112ce635705.png)

The type-ahead looks at `name` field of `exchanges` collection as below:

![screenshot from 2018-04-22 16-03-10](https://user-images.githubusercontent.com/27463355/39094028-be6011d6-4646-11e8-9056-97bdf85b7562.png)

We retrieve tagged exchanges from currencies collection, only because we do not want to show already tagged exchanges again in the typeahead.

![screenshot from 2018-04-22 16-05-31](https://user-images.githubusercontent.com/27463355/39094035-1e5ff74a-4647-11e8-8171-7cab6d3001e7.png)

If there are any tagged exchanges for this particular currency, we ask typeahead to not to include them. (in line 431, using $nin)
Only this purpose, we retrieving exchanges from currencies collection. So i think current procedure is exactly same with the requirement. Sorry if i missed something.

**Comment by chamidu-supeshala** [comment]
Currently, cannot add exchanges to currencies which don not have any previous exchanges, due to a validation issue. I'm pretty sure, everything in [/currency/x] will work properly after merging #1267

**Comment by janat08** [comment]
I guess the map error occurs where exchangesNames are produced on parent template.
https://github.com/Blockrazor/blockrazor/blob/9ebeb50389c88e1087f11d5dbe744fe12ec41672/imports/ui/pages/currencyDetail/currencyInfo.js#L27

**Comment by gazhayes** [comment]
@chamidu-supeshala Yep you got it. I'll test tomorrow but should be ok now.
