### ISSUE TITLE
problem: can't sort suspicious IP's by IP login time

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#1983]
Problem: the last login time on the duplicate account IP list is based on the user login time. This means that any IP that has ever been used by a user is pushed to the top of the list whenever that user logs in. This makes it hard to distinguish by IP address.

Solution: add a new data point: last time this IP was used. Keep the existing sort method but add this data point to the list in an extra column. It should also be added to the UX as a sort option but this whoever takes this issue (@anbud I'm guessing) can add the UX sort thing as a new issue when they have solved this one (and all the objects are there already and easily used by UX people).

**Comment by anbud** [comment]
Yap, it's me, @emurgobot claim. I'll add the sort functionality and UI/UX guys can make it pretty. :)

**Comment by anbud** [comment]
Done in #2001.

@emurgobot done

**Comment by gazhayes** [comment]
OK this isn't quite fixed. 

Sorting by the last IP access time still just sorts by the last time any user who has ever used that IP last accessed the site FROM any IP. However for it to be useful it has to be sorted by the last time the site was accessed from that IP.

Let me know if this makes sense or not

**Comment by anbud** [comment]
It should be doing exactly the thing you've described, I'll check out what's happening. It could be that missing data is causing this behavior as last access time for IPs wasn't saved until this PR.

**Comment by anbud** [comment]
@emurgobot claim

**Comment by anbud** [comment]
Fixed in #2017. Sorting should work properly even if there's data missing.
