### ISSUE TITLE
problem: [/] coins are not loaded in same order they are displayed

### ISSUE THREAD

**Issue by gazhayes** [Blockrazor/blockrazor#798]
Problem: coins are displayed in order of data quality. However they are not initially loaded by fast render in this order. So new items that load when the bottom of the page is reached are distributed through the already rendered coins based on their data quality rank.

What should happen is the initial load should be in the same order as the coins are displayed.

**Comment by anbud** [comment]
I have an idea how to fix this one, I'll take it.

**Comment by anbud** [comment]
Fixed in #828.

**Comment by gazhayes** [comment]
@anbud this still appears to be a problem

If I load / right now, ethereum classic doesn't show up. After scrolling to the bottom, ethereum classic loads and is placed at the top of the list.

**Comment by anbud** [comment]
I just found out what happened here. This was actually fixed in #828, but most of the changes are overwritten in #846.

**Comment by gazhayes** [comment]
Argh. OK. that's remarkably annoying.

**Comment by gazhayes** [comment]
It's probably easier to just revert #846

**Comment by gazhayes** [comment]
Probably broke a bunch of other stuff too.

**Comment by gazhayes** [comment]
Fixed in #851
