### ISSUE TITLE
Problem: No view for 404 error messages

### ISSUE THREAD

**Issue by AshHimself** [Blockrazor/blockrazor#87]
Problem: When a view is accessed that does not exist a white page is presented. A suitable 404 message should be presented to the user. e.g. https://blockrazor.org/fdasf

Solution: create a new flow router route for 404 error messages.

**Comment by gazhayes** [comment]
@AshHimself Have you started working on this one? If you haven't, I'll label it as a new contributor assessment because it's a nice simple one with limited scope to break other things.

**Comment by AshHimself** [comment]
I have not mate. Just raising for visibility.

**Comment by gazhayes** [comment]
Perfect, a good issue to raise!

**Comment by mutox19** [comment]
added a 404 route

**Comment by gazhayes** [comment]
As the pull request for this paid contributor assessment did not make any attempt to comply with the contribution protocol (at all) it was rejected, the issue is still available.

**Comment by madguy02** [comment]
Issue resolved and merged https://github.com/Blockrazor/blockrazor/pull/104

**Comment by madguy02** [comment]
Should this issue be removed?? as it is resolved

**Comment by gazhayes** [comment]
It's not quite resolved as you directed users to /wallet which is only for logged in users. I have fixed this in my pull request, once it is merged I will close this issue.

**Comment by madguy02** [comment]
ok great

**Comment by AshHimself** [comment]
Fixed #105
